[theme]
primaryColor = "#6366f1"        
backgroundColor = "#000"    
secondaryBackgroundColor = "#1e293b"  
textColor = "#e2e8f0"           
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = true
