OPENAI_TOKEN="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"
TOKEN_BOT="8170329541:AAF_VQGToI752OTUm4_tw2tItc91DDGiNcQ"
